global:
      scrape_interval: 15s # How frequently to scrape targets
      evaluation_interval: 15s # How frequently to evaluate rules

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090'] # Prometheus itself

      - job_name: 'node_exporter'
        static_configs:
          - targets: ['localhost:9100'] # Node Exporter for system metrics
